require("settings")
require("colourschemes-config.nightfox")
-- require("colourschemes-config.doom-one")
-- require("colourschemes-config.one-dark-pro")
-- require("colourschemes-config.onedark")
require("packer-config")
require("nvim-tree-config")
require("mappings")
require("toggleterm-config")
require("lsp-config.language-servers")
require("lsp-config.nvim-cmp")
require("lualine-config")
require("barbar-config")
require("treesitter-config")
require("autocommands")
require("autopairs-config")
require("trouble-config")
require("lsp-config.null-ls-config")
require("gitsigns-config")
require("indent-blanklines-config")
require("session-manager-config")
